CREATE DATABASE TEST_1;
USE TEST_1;

CREATE TABLE TEST(
ID INT (10),
FIRST_NAME VARCHAR(30),
LAST_NAME VARCHAR(10),
CITY VARCHAR(20),
SALARY INT(10));

SELECT * FROM TEST;

INSERT INTO TEST VALUES
(1,'BHARGAV','RAVAL','BHAVNAGAR',20000),
(2,'BHAVIK','RAVAL','NAVSARI',25000),
(1,'RAM','PATEL','SURAT',30000);

#------------------------------AUTO INCREAMENT-----------------------------------------------------------

CREATE TABLE TEST1(
ID INT AUTO_INCREMENT,
FIRST_NAME VARCHAR(30),
LAST_NAME VARCHAR(10),
CITY VARCHAR(20),
SALARY INT(10),
PRIMARY KEY (ID) 
);

INSERT INTO TEST1 VALUES
(1,'BHARGAV','RAVAL','BHAVNAGAR',20000),
(2,'BHAVIK','RAVAL','NAVSARI',25000),
(3,'RAM','PATEL','SURAT',30000);

SELECT * FROM TEST1;


INSERT INTO TEST1 (FIRST_NAME,LAST_NAME,CITY,SALARY)VALUES
('OM','RAVAL','BHAVNAGAR',40000),
('LAXMAN','DESAI','AYODHYA',50000),
('RAM','PATEL','SURAT',30000);


#------------------------------- CHECK ----------------------------------------------------------------------

CREATE TABLE TEST2(
ID INT ,
FIRST_NAME VARCHAR(30),
LAST_NAME VARCHAR(10),
CITY VARCHAR(20),
SALARY INT CHECK (SALARY < 10000)
);


INSERT INTO TEST2 VALUES
(1,'BHARGAV','RAVAL','BHAVNAGAR',7000),
(2,'BHAVIK','RAVAL','NAVSARI',5000),
(3,'RAM','PATEL','SURAT',3000);

SELECT * FROM TEST2;

#---------------------------------- UNIQUE ---------------------------------------------------------

CREATE TABLE TEST3 (
ID INT (10) NOT NULL ,
FIRST_NAME VARCHAR (30),
LAST_NAME VARCHAR (30),
CITY VARCHAR (30) UNIQUE,
SALARY INT (10));

INSERT INTO TEST3 VALUES
(1,'BHARGAV','RAVAL','BHAVNAGAR',25000),
(2,'BHAVIK','RAVAL','NAVSARI',35000),
(3,'RAM','DAVE','SURAT',15000);

SELECT * FROM TEST3;

/#------------------------------ DEFAULT ----------------------------------------------------

DROP TABLE TEST4;
CREATE TABLE TEST4 (
ID INT (10) NOT NULL ,
FIRST_NAME VARCHAR (30),
LAST_NAME VARCHAR (30),
SALARY INT (10),
CITY VARCHAR (30) DEFAULT 'BHAVNAGAR'
);

INSERT INTO TEST4 (ID,FIRST_NAME,LAST_NAME,SALARY)VALUES
(1,'BHARGAV','RAVAL',25000),
(2,'BHAVIK','RAVAL',35000),
(3,'RAM','DAVE',15000);

SELECT * FROM TEST4;

INSERT INTO TEST4 VALUES
(4,'BHARGAV','RAVAL',25000,default);

#--------------------------- FOREIGN KEY --------------------------------------------------------------

CREATE TABLE PRODUCT1(
PRODUCT_ID INT,
PRODUCT_NAME VARCHAR(20),
SHIP_DATE DATETIME,
PRIMARY KEY (PRODUCT_ID));

INSERT INTO PRODUCT1 VALUES
(101,'RUPA','2013-10-1');

SELECT * FROM PRODUCT1;

CREATE TABLE ORDER1(
ORDER_ID INT,
ORDER_DETAIL VARCHAR(20),
ORDER_DATE DATE ,
PRODUCT_ID INT, 
PRIMARY KEY (ORDER_ID),
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT1 (PRODUCT_ID));

INSERT INTO ORDER1 VALUES
(1,'CLOTHER','2013-10-1',101);

SELECT * FROM ORDER1;

/* TO RETRIEVE THE SECOND-HIGHEST SALARY FROM THE TABLE*/

SELECT MAX(SALARY) FROM EMPLOYEE WHERE SALARY <
(SELECT MAX(SALARY) FROM EMPLOYEE);