CREATE DATABASE NEW1;
USE NEW1;

CREATE TABLE STUDENT (
S_ID INT PRIMARY KEY,
S_NAME VARCHAR(30));

INSERT INTO STUDENT VALUES
(1,'JACK'),
(2,'RUTVUK'),
(3,'JASPREET'),
(4,'PRAVEEN'),
(5,'BISA'),
(6,'SURAJ');

CREATE TABLE MARKS (
SCHOOL_ID INT PRIMARY KEY,
S_ID INT,
SCORE INT,
STATUS VARCHAR(40));

INSERT INTO MARKS VALUES
(1004,1,23,'FAIL'),
(1008,6,95,'PASS'),
(1012,2,97,'PASS'),
(1016,7,67,'PASS'),
(1020,3,100,'PASS'),
(1025,8,73,'PASS'),
(1030,4,88,'PASS'),
(1035,9,13,'FAIL'),(1040,5,16,'FAIL'),
(1050,10,53,'PASS');


CREATE TABLE DETAILS(
ADDRESS_CITY VARCHAR (30),
EMAIL_ID VARCHAR (40),
SCHOOL_ID INT,
ACCOMPLISHMENT VARCHAR (50));

INSERT INTO DETAILS VALUES 
('BANGALORE','JSINGH@JTP.COM',1020,'ACM ICPC SELECTED'),
('HYDERABAD','PARVEEN@JTP.COM',1030,'GEEK OF THE MONTH'),
('DELHI','RITHVIK@JTP.COM',1012,'IOI FINALIST'),
('CHENNAI','OM@JTP.COM',1111,'GEEK OF THE MONTH'),
('BANGALORE','SURAJ@JTP.COM',1008,'IOI FINALIST'),
('MUMBAI','SASUKEH@JTP.COM',2211,'MADE A ROBOT'),
('AHMEDABAD','ITACHI@JTP.COM',1172,'CODE JAM FINALIST'),
('JAIPUR','KUMAR@JTP.COM',1972,'KVPY FINALIST');


SELECT S_NAME,SCORE,STATUS,ADDRESS_CITY,EMAIL_ID,ACCOMPLISHMENT
FROM STUDENT AS A 
INNER JOIN MARKS AS B 
ON A.S_ID = B.S_ID 
INNER JOIN DETAILS AS C
ON C.SCHOOL_ID = B.SCHOOL_ID;

CREATE TABLE PARENTS (
PAR_ID INT PRIMARY KEY,
PAR_NAME VARCHAR(30),
ADDRESS_CITY VARCHAR (30));

INSERT INTO PARENTS VALUES 
(1,'BHARGAV BHAI','BANGALORE'),
(2,'BHAVIK BHAI','JAIPUR'),
(3,'RAMESH BHAI','HYDERABAD'),
(4,'PARTH BHAI','AHMEDABAD'),
(5,'ROHIT BHAI','MUMBAI'),
(6,'DHAVAL BHAI','DELHI');

SELECT * FROM PARENTS;

SELECT S_NAME,SCORE,STATUS,C.ADDRESS_CITY AS CITY,EMAIL_ID,ACCOMPLISHMENT,PAR_NAME
FROM STUDENT AS A 
INNER JOIN MARKS AS B 
ON A.S_ID = B.S_ID 
INNER JOIN DETAILS AS C
ON C.SCHOOL_ID = B.SCHOOL_ID
INNER JOIN PARENTS AS D
ON D.ADDRESS_CITY = C.ADDRESS_CITY;

/* JOIN 4 TABLE */

SELECT *
FROM STUDENT AS A 
LEFT JOIN MARKS AS B 
ON A.S_ID = B.S_ID 
RIGHT JOIN DETAILS AS C
ON C.SCHOOL_ID = B.SCHOOL_ID
RIGHT JOIN PARENTS AS D
ON D.ADDRESS_CITY = C.ADDRESS_CITY;


SELECT S_ID,S_NAME FROM STUDENT
UNION ALL
SELECT SCORE,STATUS FROM MARKS
UNION ALL
SELECT ADDRESS_CITY,ACCOMPLISHMENT FROM DETAILS
UNION ALL
SELECT PAR_NAME,PAR_ID FROM PARENTS;

#####################################################################################################################

DELIMITER $$
CREATE PROCEDURE BK(A INT,OUT B FLOAT)
BEGIN 
     SET B = SQRT(A);
END $$
DELIMITER ;

CALL BK(100,@B);
SELECT @B;

DROP PROCEDURE P1;
DELIMITER $$
CREATE PROCEDURE P1(A INT,B INT,C INT,OUT D FLOAT)
BEGIN
 SET D = POWER(A,B,C);
END $$
DELIMITER ;

CALL P1(5,5,5,@D);
SELECT @D;

 DELIMITER $$
CREATE PROCEDURE SETCOUNTER1(INOUT COUNTER INT,IN INC INT)
BEGIN
 SET COUNTER = COUNTER + INC;
 END $$

 SET @COUNTER = 12;
 CALL SETCOUNTER1(@COUNTER,6);
 SELECT @COUNTER;
 
  DELIMITER $$
 CREATE PROCEDURE USER_VAR4()
 BEGIN
  SET @A = 20;
  SET @B = 10;
  SELECT @A,@B,@A-@B,@A+@B,@A*@B,@A%@B;
END $$

CALL USER_VAR4;