create database h;
use h;
create table sales(
sale_id int,
firstname varchar(20),
lastname varchar(23));

insert into sales values
(101,"bhargav","raval");

select * from sales;

insert into sales values
(102,"bhavik","raval"),(103,"ram","raghuvanshi");

USE SAKILA;
SELECT * FROM CUSTOMER;
SELECT CUSTOMER_ID, LAST_UPDATE FROM CUSTOMER;
SELECT * FROM CUSTOMER LIMIT 15;
SELECT DISTINCT(ACTIVE) FROM CUSTOMER;
SELECT DISTINCT(STORE_ID) FROM CUSTOMER;
SELECT * FROM CUSTOMER WHERE FIRST_NAME = "BHARGAV";
SELECT LAST_NAME,EMAIL FROM CUSTOMER WHERE FIRST_NAME = "BHARGAV";
SELECT * FROM CUSTOMER WHERE FIRST_NAME = "BHARGAV";
SELECT * FROM CUSTOMER WHERE ACTIVE = 0;
SELECT * FROM CUSTOMER WHERE ADDRESS_ID = 451;
SELECT FIRST_NAME,LAST_NAME,EMAIL FROM CUSTOMER WHERE ADDRESS_ID = 540;
SELECT * FROM CUSTOMER WHERE ADDRESS_ID <= 20;
SELECT * FROM CUSTOMER WHERE ADDRESS_ID >= 10;

#----- BETWEEN,OR,AND ---------

SELECT CUSTOMER_ID,FIRST_NAME,LAST_NAME FROM CUSTOMER WHERE CUSTOMER_ID BETWEEN 20 AND 25;
SELECT * FROM CUSTOMER WHERE FIRST_NAME = 'MERY' OR LAST_NAME = 'SMITH'; # DONO  MESE 1 CONDITION RIGHT HONI CHAHIYE
SELECT * FROM CUSTOMER WHERE FIRST_NAME = 'LISA' AND LAST_NAME = 'ANDERSON'; # DONO CANDITION RIGHT HONI CHAHIYR

#-------- UPDATE ----------

UPDATE CUSTOMER SET FIRST_NAME = 'BHARGAV' WHERE LAST_NAME = 'SMITH';
UPDATE CUSTOMER SET LAST_NAME = 'RAVAL' WHERE FIRST_NAME = 'BHARGAV';
UPDATE CUSTOMER SET FIRST_NAME = 'BHAVIK' WHERE LAST_NAME = 'CULP';

#--------- ORDER BY ------------

SELECT * FROM CUSTOMER WHERE FIRST_NAME = "BHARGAV";
SELECT FIRST_NAME,LAST_NAME,ADDRESS_ID FROM CUSTOMER ORDER BY FIRST_NAME DESC; # Z TO A , 10 TO 1
SELECT FIRST_NAME,LAST_NAME,ADDRESS_ID FROM CUSTOMER ORDER BY FIRST_NAME ASC;  # A TO Z BY DEFULT, 1 TO 10
SELECT * FROM CUSTOMER ORDER BY CUSTOMER_ID DESC;

SELECT FIRST_NAME,LAST_NAME,ADDRESS_ID,STORE_ID FROM CUSTOMER WHERE STORE_ID = 1 ORDER BY ADDRESS_ID DESC LIMIT 3;

UPDATE FILM SET RELEASE_YEAR = 2007 WHERE RELEASE_YEAR = 2006;

#-------------------------- AGRIGET FUNCTION --------------------------------------------------------

SELECT MIN(ADDRESS_ID) FROM CUSTOMER;
SELECT MAX(ADDRESS_ID) FROM CUSTOMER;
SELECT SUM(ADDRESS_ID) FROM CUSTOMER;
SELECT AVG(ADDRESS_ID) FROM CUSTOMER;
SELECT COUNT(ADDRESS_ID) FROM CUSTOMER;

SELECT FIRST_NAME, LAST_NAME FROM CUSTOMER WHERE ADDRESS_ID =(SELECT MIN(ADDRESS_ID) FROM CUSTOMER);
SELECT * FROM CUSTOMER WHERE ADDRESS_ID =(SELECT MAX(ADDRESS_ID) FROM CUSTOMER);

#------------------------------- LIKE, IN  ------------------------

SELECT * FROM CUSTOMER WHERE FIRST_NAME LIKE "%R"; # LAST ME JO VALUE DENGE VO
SELECT * FROM CUSTOMER WHERE FIRST_NAME LIKE "R%"; # FIRST ME JO VALUE DENGE VO
SELECT * FROM CUSTOMER WHERE FIRST_NAME LIKE "J%A";
SELECT * FROM CUSTOMER WHERE FIRST_NAME LIKE "%NI%";
SELECT * FROM CUSTOMER WHERE FIRST_NAME LIKE "A______%"; # ETANEHI LENGH KA VALUE CHAHIYR
SELECT * FROM CUSTOMER WHERE FIRST_NAME LIKE "_____";
SELECT * FROM CUSTOMER WHERE STORE_ID LIKE "A_____";
SELECT * FROM CUSTOMER WHERE LENGTH(FIRST_NAME) = 5; # ETANEHI LENGH KA VALUE CHAHIYR
SELECT * FROM CUSTOMER WHERE FIRST_NAME LIKE 'A%' AND LENGTH(FIRST_NAME) = 5;
SELECT * FROM CUSTOMER WHERE CUSTOMER_ID IN (1,2,3,4);



SELECT STORE_ID,COUNT(STORE_ID) FROM CUSTOMER GROUP BY STORE_ID;

USE WORLD;
SELECT * FROM COUNTRY;
SELECT COUNT(*) FROM COUNTRY;
SELECT CONTINENT ,MAX(SURFACEAREA)FROM COUNTRY group by CONTINENT ;
SELECT NAME,CONTINENT,POPULATION FROM COUNTRY WHERE SURFACEAREA = (SELECT MAX(POPULATION) FROM COUNTRY);

SELECT CONTINENT,SUM(POPULATION) FROM COUNTRY GROUP BY CONTINENT;
SELECT SUM(POPULATION) FROM COUNTRY ;

SELECT * FROM COUNTRY WHERE CONTINENT =  "Asia";

SELECT CONTINENT,SUM(POPULATION) AS A FROM COUNTRY GROUP BY CONTINENT order by A ASC ;
SELECT REGION,SUM(POPULATION) AS Q FROM COUNTRY GROUP BY REGION order by Q ASC;

SELECT * FROM COUNTRY WHERE NAME LIKE "A%";

SELECT MAX(SURFACEAREA) FROM COUNTRY;

SELECT MIN(POPULATION) FROM COUNTRY;

SELECT POPULATION FROM COUNTRY LIMIT 10;

SELECT CONTINENT,MAX(GNP) FROM COUNTRY GROUP BY CONTINENT;

SELECT REGION, CONTINENT,POPULATION FROM COUNTRY WHERE
POPULATION =(SELECT MIN(POPULATION) FROM COUNTRY);

SELECT DISTINCT CONTINENT FROM COUNTRY;

SELECT REGION, CONTINENT,POPULATION FROM COUNTRY WHERE
POPULATION =(SELECT MAX(POPULATION) FROM COUNTRY);

SELECT NAME,CONTINENT FROM COUNTRY WHERE 
SURFACEAREA = (SELECT MAX(SURFACEAREA)FROM COUNTRY) OR 
POPULATION = (SELECT MAX(POPULATION)FROM COUNTRY);

SELECT * FROM COUNTRY WHERE NAME LIKE 'A%' OR LENGTH(NAME) = 3;
SELECT * FROM COUNTRY WHERE NAME LIKE "A___";

SELECT LENGTH(NAME) AS A,LEFT(NAME,3) AS B FROM COUNTRY;

SELECT * FROM FILM;
SELECT DISTINCT (RELEASE_YEAR) FROM FILM;

SELECT TITLE,RENTAL_DURATION FROM FILM WHERE RENTAL_DURATION = (SELECT MAX(RENTAL_DURATION)FROM FILM);

SELECT * FROM FILM  WHERE
LENGTH =(SELECT MAX(LENGTH) FROM FILM);

SELECT * FROM FILM WHERE TITLE LIKE "A%"; 

SELECT DISTINCT(LANGUAGE_ID) FROM FILM;

SELECT DISTINCT(RETING) FROM FILM;

SELECT TITLE,MAX(RENTAL_DURATION) FROM FILM GROUP BY TITLE;

SELECT TITLE,RENTAL_DURATION FROM FILM WHERE RENTAL_DURATION = (SELECT DISTINCT(RENTAL_DURATION) FROM FILM);

SELECT * FROM FILM WHERE SPECIAL_FEATURES = "DELETED SCENES";

UPDATE FILM SET RELEASE_YEAR = 2007 WHERE RELEASE_YEAR = 2006;
UPDATE FILM SET TITLE = "BHARGAV" WHERE TITLE = "ALI FOREVER";


SELECT RENTAL_RATE,RATING FROM FILM WHERE RATING = (SELECT MIN(RATING) FROM FILM);

SELECT * FROM FILM WHERE TITLE LIKE "B%" AND LENGTH(TITLE)= 7;

SELECT * FROM FILM WHERE LENGTH(TITLE)= 10;


