CREATE DATABASE NTILE_PRACTICE;
USE NTILE_PRACTICE;


CREATE TABLE STUDENT(
ID INT PRIMARY KEY,
NAME VARCHAR (255),
PERCENTAGE INT);

INSERT INTO Student
VALUES (1,'Atul',90),
(2,'Vishal',91),
(3,'Shailesh',3),
(4,'Niraj',92),
(5,'Chetan',89),
(6,'Sangram',87),
(7,'Rohit',87),
(8,'Prashant',93),
(9,'Ravi' ,91),
(10,'Akansha',94);


CREATE TABLE STUDENT1(
ID INT PRIMARY KEY,
NAME VARCHAR (255),
PERCENTAGE INT);

INSERT INTO Student1
VALUES (1,'Atul',90),
(2,'Vishal',91),
(3,'Shailesh',3),
(4,'Niraj',92),
(5,'Chetan',89),
(6,'Sangram',87),
(7,'Rohit',87),
(8,'Prashant',93),
(9,'Ravi' ,91),
(10,'Akansha',94);
SELECT * FROM STUDENT1;

# ORD 
SELECT ID,NAME, PERCENTAGE,NTILE(3) OVER (ORDER BY PERCENTAGE DESC) AS A FROM STUDENT1;

# EVEN
INSERT INTO STUDENT VALUES (11,'BHARGAV',98);

SELECT ID,NAME, PERCENTAGE,NTILE(3) OVER (ORDER BY PERCENTAGE DESC) AS A FROM STUDENT;

# 3. NTILE 

CREATE TABLE STUDENT2(
ID INT PRIMARY KEY,
NAME VARCHAR (255),
SUBJECT VARCHAR (60),
MARK INT);

INSERT INTO Student2
VALUES (1,'Atul','ENGLESH',90),
(2,'Vishal','ENGLESH',91),
(3,'Shailesh','ENGLESH',63),
(4,'Niraj','ENGLESH',92),
(5,'Chetan','ENGLESH',89),
(6,'Sangram','MATHS',87),
(7,'Rohit','MATHS',87),
(8,'Prashant','MATHS',93),
(9,'Ravi' ,'MATHS',91),
(10,'Akansha','MATHS',94);

SELECT * FROM STUDENT2;

SELECT ID,NAME,SUBJECT,MARK,NTILE(3) OVER
(PARTITION BY SUBJECT ORDER BY MARK DESC) AS A FROM STUDENT2;

