CREATE DATABASE ROLLUP1;
USE ROLLUP1;

CREATE TABLE EMPLOYEE(
ID INT,
`NAME` VARCHAR (50)NOT NULL,
GENDER VARCHAR (50) NOT NULL,
SALARY INT NOT NULL,
DEPARTMENT VARCHAR (50) NOT NULL );

INSERT INTO employee VALUES
  (1, 'jalpesh', 'Male', 5000, 'Sales'),
  (2, 'sneha', 'Female', 6000, 'HR'),
  (3, 'Karti', 'Female', 7500, 'IT'),
  (4, 'suman', 'Male', 6500, 'Marketing'),
  (5, 'viha', 'Female', 5500, 'Finance'),
  (6, 'vishal', 'Male', 8000, 'Sales'),
  (7, 'Viki', 'Male', 7200, 'HR'),
  (8, 'Viysni', 'Female', 6600, 'IT'),
  (9, 'alpa', 'Female', 5400, 'Marketing'),
  (10, 'aesha', 'Female', 6300, 'Finance'),
  (11, 'vishal', 'Male', 5700, 'Sales'),
  (12, 'Pratik', 'Male', 7000, 'HR'),
  (13, 'janvi', 'Female', 7100, 'IT'),
  (14, 'prapti', 'Female', 6800,'Marketing'),
  (15, 'axil', 'Male', 5000, 'Finance');
  
  
SELECT * FROM EMPLOYEE;
  
SELECT SUM(SALARY),GENDER FROM EMPLOYEE GROUP BY GENDER;
  
SELECT SUM(SALARY),GENDER FROM EMPLOYEE GROUP BY GENDER WITH ROLLUP;

SELECT SUM(SALARY),COALESCE(GENDER, "SUM OF GENDER") AS A FROM EMPLOYEE GROUP BY GENDER WITH ROLLUP;


SELECT SUM(SALARY),DEPARTMENT FROM EMPLOYEE GROUP BY DEPARTMENT;


  SELECT SUM(SALARY),DEPARTMENT FROM EMPLOYEE GROUP BY DEPARTMENT  WITH ROLLUP;
  
    SELECT SUM(SALARY),COALESCE(DEPARTMENT, "SUM OF DEPT")AS A FROM EMPLOYEE GROUP BY DEPARTMENT  WITH ROLLUP;

SELECT DEPARTMENT,GENDER,SUM(SALARY) FROM EMPLOYEE GROUP BY DEPARTMENT,GENDER WITH ROLLUP;

SELECT COALESCE(DEPARTMENT,'ALL DEPT')AS DEPARTMENT,
COALESCE(GENDER,'SUM OF SALARY') AS GENDER ,
SUM(SALARY) FROM EMPLOYEE 
GROUP BY DEPARTMENT,GENDER 
WITH ROLLUP;



# CUBE IN NOT SUPPORT IN MYSQL WORKBENCH.

SELECT COALESCE(DEPARTMENT,'ALL DEPT')AS DEPARTMENT,
COALESCE(GENDER,'SUM OF SALARY') AS GENDER ,
SUM(SALARY) 
FROM EMPLOYEE 
GROUP BY DEPARTMENT,GENDER WITH CUBE;

