CREATE DATABASE SP1;
USE SP1;

/* SQRT ROOT*/

DELIMITER $$
CREATE PROCEDURE SQRT_ROOT(A INT,OUT B FLOAT)
BEGIN
 SET B = SQRT(A);
 END $$
 DELIMITER ;
 
 CALL SQRT_ROOT(64,@B);
 SELECT @B;

/* POWER ROOT*/
 
 DELIMITER $$
CREATE PROCEDURE POWER_ROOT1(A INT,B INT,OUT C FLOAT)
BEGIN
 SET C = POWER(A,B);
 END $$
 DELIMITER ;
 
 CALL POWER_ROOT1(3,2,@C);
 SELECT @C;
 
 /* SETCOUNTER */
 
 DELIMITER $$
CREATE PROCEDURE SETCOUNTER(INOUT COUNTER INT,IN INC INT)
BEGIN
 SET COUNTER = COUNTER + INC;
 END $$

 SET @COUNTER = 2;
 CALL SETCOUNTER(@COUNTER,6);
 SELECT @COUNTER;
 
 DELIMITER $$
 CREATE PROCEDURE USER_VAR1()
 BEGIN
  SET @A = 20;
  SET @B = 10;
  SELECT @A,@B,@A-@B,@A+@B;
END $$

CALL USER_VAR1;

 DELIMITER $$
 CREATE PROCEDURE USER_VAR3()
 BEGIN
  SET @A = 'RAVAL';
  SET @B = 'BHARGAV';
  SELECT @A,@B;
END $$

CALL USER_VAR3;

USE SAKILA;
SELECT * FROM CUSTOMER;


DELIMITER $$
CREATE PROCEDURE A1(IN DEPT_ID INT)
BEGIN
  SELECT CUSTOMER_ID,FIRST_NAME
  FROM CUSTOMER
  WHERE CUSTOMER_ID = DEPT_ID;
END $$
DELIMITER ;

CALL A1 (1);

DELIMITER $$
CREATE PROCEDURE A2(IN DEPT_ID INT)
BEGIN
  SELECT CUSTOMER_ID,FIRST_NAME,LAST_NAME
  FROM CUSTOMER
  WHERE CUSTOMER_ID = DEPT_ID;
END $$
DELIMITER ;

CALL A2(222);

CREATE TABLE EMPLOYEE (
EMPLOYEE_ID INT AUTO_INCREMENT PRIMARY KEY,
EMPLOYEE_NAME VARCHAR (100) NOT NULL,
DEPARTMENT_ID INT NOT NULL,
SALARY DECIMAL(10.2) NOT NULL );

INSERT INTO EMPLOYEE (EMPLOYEE_NAME,DEPARTMENT_ID,SALARY)VALUE
('ALICE JOHNSON',101,60000.00),
('BOB SMITH',102,55000.00),
('CHARLIE BROWN',103,45000.00),
('DIANA PRICE',101,70000.00),
('EDWARD NORTON',102,50000.00),
('FIONA APPLE',103,52000.00),
('GEORGE MARTIN',101,62000.00),
('HANNAH LEE',104,58000.00),
('IAN WRIGHT',104,47000.00),
('JULIA ROBERTS',102,65000.00),
('KEVIA HART',103,54000.00),
('LIAM NEESON',101,63000.00),
('MONICA BELL',104,51000.00),
('NATHAN DRAKE',101,72000.00),
('OLIVIA WILDE',102,69000.00),
('PAUL WALKER',103,48000.00),
('QUINCY ADAMS',104,53000.00),
('RACHEL GREEN',101,75000.00),
('STEVE ROGERS',102,46000.00),
('TINA FEY',103,61000.00);


SELECT * FROM EMPLOYEE ;

DROP PROCEDURE EMP7;
DELIMITER $$

CREATE PROCEDURE EMP(
    IN EMP_NAME VARCHAR(100),
    IN DEPT_ID INT,
    IN SALARY DECIMAL(10,2) 
)
BEGIN
     INSERT INTO EMPLOYEE (EMPLOYEE_NAME,DEPARTMENT_ID,SALARY)
     VALUES (EMP_NAME,DEPT_ID,SALARY);
END $$

DELIMITER ;

CALL EMP('BHARGTAV',101,80000.00);
CALL EMP();


DELIMITER $$

CREATE PROCEDURE EMP1(
     IN EMP_ID INT,
    IN NEW_SALARY DECIMAL(10,2) 
)
BEGIN
     UPDATE EMPLOYEE
SET SALARY = NEW_SALARY
WHERE EMPLOYEE_ID = EMP_ID;

END $$

DELIMITER ;

CALL EMP1(1,80000.00);


DELIMITER $$

CREATE PROCEDURE EMP3()
BEGIN
    SELECT DEPARTMENT_ID,COUNT(EMPLOYEE_ID) FROM EMPLOYEE GROUP BY DEPARTMENT_ID ;

END $$

DELIMITER ;

CALL EMP3;



DELIMITER $$

CREATE PROCEDURE EMP4(
   IN EMP_ID INT)
BEGIN
    DELETE FROM EMPLOYEE
    WHERE EMPLOYEE_ID = EMP_ID;
END $$

DELIMITER ;

CALL EMP4(1);
SELECT EMP4;

SELECT * FROM EMPLOYEE;

DELIMITER $$

CREATE PROCEDURE EMP5(
    IN AMOUNT INT)
BEGIN
       SELECT * FROM EMPLOYEE
       WHERE SALARY > AMOUNT;
END $$

DELIMITER ;

CALL EMP5(50000.00);

DROP PROCEDURE EMP7;


DELIMITER $$

CREATE PROCEDURE EMP6()
BEGIN
       SELECT * FROM EMPLOYEE
       WHERE SALARY BETWEEN 50000.00 AND 70000.00;
END $$

DELIMITER ;

CALL EMP6;


DELIMITER $$

CREATE PROCEDURE EMP7(
      IN DEPT_ID INT,
      IN PERCENTAGE DECIMAL (5,2))
BEGIN
       UPDATE EMPLOYEE
       SET SALARY = SALARY + (SALARY * (PERCENTAGE / 100)) 
       WHERE DEPARTMENT_ID = DEPT_ID ;
END $$

DELIMITER ;

CALL EMP7(101,10);

DELIMITER $$

CREATE PROCEDURE EMP9(
      IN DEPT_ID INT
	)
BEGIN
       DELETE FROM EMPLOYEE
       WHERE DEPARTMENT_ID = DEPT_ID;
       SELECT * FROM EMPLOYEE;
END $$

DELIMITER ;

CALL EMP9(101);

SELECT * FROM EMPLOYEE;


DELIMITER $$

CREATE PROCEDURE EMP21(
	)
BEGIN
      SELECT * FROM EMPLOYEE WHERE SALARY >(SELECT AVG(SALARY) AS A FROM EMPLOYEE);
      SELECT * FROM EMPLOYEE;
END $$

DELIMITER ;

CALL EMP21();